apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: reallifeafrica-org-tls
spec:
  secretName: reallifeafrica-org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: reallifeafrica.org
  dnsNames:
    - reallifeafrica.org
    - www.reallifeafrica.org
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - reallifeafrica.org
          - www.reallifeafrica.org
